// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	UserInfo
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type FOO int32

const (
	FOO_x FOO = 0
)

var FOO_name = map[int32]string{
	0: "x",
}
var FOO_value = map[string]int32{
	"x": 0,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto1.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UserInfo struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Length           *int32  `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Cnt              *int32  `protobuf:"varint,3,opt,name=cnt" json:"cnt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto1.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *UserInfo) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *UserInfo) GetCnt() int32 {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return 0
}

func init() {
	proto1.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto1.RegisterEnum("proto.FOO", FOO_name, FOO_value)
}

func init() { proto1.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x16, 0x5c, 0x1c, 0xa1, 0xc5,
	0xa9, 0x45, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0xfc, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x42, 0x7c, 0x5c, 0x6c, 0x39, 0xa9, 0x79, 0xe9, 0x25,
	0x19, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x42, 0xdc, 0x5c, 0xcc, 0xc9, 0x79, 0x25, 0x12, 0xcc,
	0x20, 0x8e, 0x16, 0x0f, 0x17, 0xb3, 0x9b, 0xbf, 0xbf, 0x10, 0x2b, 0x17, 0x63, 0x85, 0x00, 0x03,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xe1, 0xe9, 0x26, 0x5b, 0x00, 0x00, 0x00,
}
